server:
  port: 7000
  servlet:
    session.timeout: 300

logging:
  level:
    org.springframework.web: DEBUG


spring:
  #Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  #Thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 0
    cache: false

  #redis
  redis:
      cluster:
        nodes: namenode22:6379,datanode23:6379,datanode24:6379
        max-redirects: 6
      timeout: 300000
      jedis:
        pool:
          max-active: 8
          max-wait: 100000
          max-idle: 8
          min-idle: 0
#  redis:
#    database: 0
#    host: 127.0.0.1
#    jedis:
#      pool:
#        max-active: 1024
#        max-idle: 200
#        max-wait: 10000
#        min-idle: 0
#    password:
#    port: 6379
#    timeout: 10000

#mybatis
mybatis:
  type-aliases-package: cn.zifangsky.mapper
  mapper-locations: classpath:cn/zifangsky/mapper/xml/*.xml